/**
 * The ΑΗΦΥ date fields.
 *
 * There is no candidate pass and no scoring here. The repository labels its
 * dates — `Ημερομηνία Λήψης Δείγματος` is the collection date and
 * `Ημερομηνία Αποτελέσματος` the result date — so the only work left is turning
 * one repository-formatted field into a civil date, and refusing anything that
 * is not one.
 */

/** `dd-mm-yyyy`, exactly: the repository pads both day and month to two digits. */
const DOCUMENT_DATE = /^(\d{2})-(\d{2})-(\d{4})$/u;

/**
 * Convert one printed `dd-mm-yyyy` field to a `YYYY-MM-DD` civil date, or
 * `null` if it is not a date the calendar has.
 *
 * Day-first needs no disambiguation: the field is generated by the repository,
 * not printed as prose by a laboratory, so `03-04-2025` is 3 April and there is
 * no second reading to flag. That is why nothing here returns an ambiguity.
 *
 * The result carries no time. `CollectedAt` has a `'minute'` precision, but it
 * exists to separate two Reports collected on the same day, and that time comes
 * from the user during review — the document never states one.
 *
 * Rejection is strict rather than forgiving. A month of `13` or a `31-02` is a
 * document that is not what it claims to be, and Pass V turns that into a
 * `missing-date` rejection at attach; silently coercing it would hand review a
 * confident date that no laboratory printed.
 */
export function parseDocumentDate(raw: string): string | null {
  const match = DOCUMENT_DATE.exec(raw.trim());
  if (match === null) {
    return null;
  }

  const [, day, month, year] = match as unknown as [string, string, string, string];
  const dayNumber = Number(day);
  const monthNumber = Number(month);
  const yearNumber = Number(year);

  if (monthNumber < 1 || monthNumber > 12 || dayNumber < 1) {
    return null;
  }

  // Day 0 of the following month is the last day of this one, which is what
  // makes February fall out of the same expression as every other month.
  const daysInMonth = new Date(Date.UTC(yearNumber, monthNumber, 0)).getUTCDate();
  if (dayNumber > daysInMonth) {
    return null;
  }

  return `${year}-${month}-${day}`;
}
